server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: hse-marketplace
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: admin
    password: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 30000
      minimum-idle: 3
      maximum-pool-size: 10
      connection-timeout: 10000
      connection-test-query: select 1
      schema: public
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yaml
  docker:
    compose:
      enabled: false